INSERT INTO categoria (id, titulo, leyes_aplicables) VALUES
('250101-AAAAAA', 'Carpintería', 'Ley de servicios domésticos'),
('250101-BBBBBB', 'Reparación de techos', 'Norma de seguridad 2020'),
('250101-CCCCCC', 'Limpieza', 'Reglamento de sanidad'),
('250101-DDDDDD', 'Puertas', 'Ley de accesibilidad'),
('250101-EEEEEE', 'Cableado eléctrico', 'Reglamento electrotécnico de baja tensión'),
('250101-FFFFFF', 'Instalación de ventiladores', 'Normas de seguridad en el hogar'),
('250101-GGGGGG', 'Reparación de cercas', 'Ley de propiedad privada'),
('250101-HHHHHH', 'Sistemas de seguridad para el hogar', 'Ley de protección del consumidor'),
('250101-IIIIII', 'Instalación de aislamiento', 'Norma térmica nacional'),
('250101-JJJJJJ', 'Reparaciones de lámparas', 'Norma de seguridad eléctrica'),
('250101-KKKKKK', 'Mudanzas', 'Reglamento de transporte'),
('250101-LLLLLL', 'Pintura', 'Ley de productos químicos'),
('250101-MMMMMM', 'Control de plagas', 'Reglamento de salud pública'),
('250101-NNNNNN', 'Reparaciones de fontanería', 'Norma de instalaciones hidráulicas'),
('250101-OOOOOO', 'Techado', 'Norma de materiales de construcción'),
('250101-PPPPPP', 'Instalación de estanterías', 'Reglamento de seguridad doméstica'),
('250101-QQQQQQ', 'Paneles solares', 'Norma de energías renovables'),
('250101-RRRRRR', 'Insonorización', 'Reglamento acústico'),
('250101-SSSSSS', 'Reparación de sistemas de riego', 'Ley agrícola nacional'),
('250101-TTTTTT', 'Reparación de ventanas', 'Norma de eficiencia energética');
